### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by TheAlexLichter** [lunelson/nuxt-issue-3106#1]
Can't start up the website, because `data/site` and `data/routes` are missing.

UPDATE: Removing corresponding lines resolved it, but dependencies are still missing (`data/books`)

**Comment by lunelson** [comment]
Sorry, I knew I was going to miss something. `data` is ignored in my project cause it's the result of another script. It's in the repo now

**Comment by TheAlexLichter** [comment]
Yup, now I can repro it.
Thanks :relaxed:
